package br.com.imovelhunter.enums;

/**
 * Created by BOTTOMUP 05 on 11/11/2014.
 */
public enum Parametros {

	SERIAL_DISPOSITIVO,CHAVE_GCM,SENHA,LOGIN, UF_JSON, CIDADE_JSON, FILTRO_JSON, CLIENTE_JSON, MENSAGEM_JSON,
    ANUNCIANTE_JSON, USUARIO_JSON , USUARIO_BLOQUEADO, USUARIO_BLOQUEADOR,USUARIO_ADICIONADOR,USUARIO_ADICIONADO,
    USUARIO_REMOVEDOR,USUARIO_REMOVIDO

}
