package br.com.imovelhunter.enums;


public enum Requisicao {

	LISTAR_IMOVEIS,CADASTRA_GCM, LOGAR, LISTAR_UFS, LISTAR_CIDADE_PELA_UF, LISTAR_BAIRRO_PELA_CIDADE, FILTRAR_IMOVEIS, CADASTRA_CLIENTE,
    ENVIAR_MENSAGEM, BUSCAR_USUARIO_POR_ANUNCIANTE

}
