package br.com.imovelhunter.enums;


public enum Requisicao {

	LISTAR_IMOVEIS,CADASTRA_GCM, LOGAR, LISTAR_UFS, LISTAR_CIDADE_PELA_UF, LISTAR_BAIRRO_PELA_CIDADE, FILTRAR_IMOVEIS, CADASTRA_CLIENTE,
    ENVIAR_MENSAGEM, BUSCAR_USUARIO_POR_ANUNCIANTE, STATUS_BLOQUEIO,LISTAR_CONTATOS_DO_USUARIO,LISTAR_CONTATOS_BLOQUEADOS_DO_USUARIO,
    STATUS_DESBLOQUEIO,ADICIONAR_USUARIO, USUARIO_E_ADICIONADO, USUARIO_E_BLOQUEADO, CADASTRA_PERFIL_IMOVEL, LISTAR_PERFIS_CADASTRADOS, REMOVER_PERFIL_CADASTRADO, LISTAR_IMOVEIS_ANUNCIANTE, REMOVER_USUARIO

}
